-- JPA가 관리하지 않는 현재 테이블과 단일 상태 행의 개발용 초기화.
-- 재시작 시 테이블과 기존 행은 유지.
CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID),
    UNIQUE KEY SPRING_SESSION_IX1 (SESSION_ID),
    KEY SPRING_SESSION_IX2 (EXPIRY_TIME),
    KEY SPRING_SESSION_IX3 (PRINCIPAL_NAME)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS admin_auth_state (
    id TINYINT NOT NULL,
    config_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    auth_version BIGINT NOT NULL,
    last_totp_step BIGINT NULL,
    failure_count INT NOT NULL,
    locked_until DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_admin_auth_state_id CHECK (id = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO admin_auth_state (id, config_fingerprint, auth_version, last_totp_step, failure_count)
VALUES (1, REPEAT('0', 64), 0, NULL, 0);

CREATE TABLE IF NOT EXISTS admin_recovery_codes (
    code_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    consumed_at DATETIME(6) NULL,
    PRIMARY KEY (code_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS deployment_state (
    singleton_id TINYINT NOT NULL PRIMARY KEY,
    operation_id VARCHAR(36) NULL,
    status VARCHAR(16) NOT NULL,
    run_id VARCHAR(32) NULL,
    run_attempt INT NULL,
    last_successful_operation_id VARCHAR(36) NULL,
    html_url VARCHAR(512) NULL,
    error_message VARCHAR(512) NULL,
    source VARCHAR(32) NULL,
    version BIGINT NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT chk_deployment_singleton CHECK (singleton_id = 1)
);
INSERT IGNORE INTO deployment_state (singleton_id, status, version) VALUES (1, 'IDLE', 0);

INSERT IGNORE INTO content_state (id) VALUES (1);
